In [24]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_csv("C:/Users/dell/Desktop/Loan_Default_Risk_Prediction/data/processed/loan_cleaned.csv")

In [26]:
categorical_columns = df.select_dtypes(include='object').columns

categorical_columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'Property_Area', 'Loan_Status'],
      dtype='object')

In [27]:
numerical_columns = df.select_dtypes(exclude='object').columns

numerical_columns

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History'],
      dtype='object')

In [28]:
for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].unique())

Gender
['Male' 'Female']

Married
['No' 'Yes']

Dependents
['0' '1' '2' '3+']

Education
['Graduate' 'Not Graduate']

Self_Employed
['No' 'Yes']

Property_Area
['Urban' 'Rural' 'Semiurban']

Loan_Status
['Y' 'N']

In [29]:
# ==========================================
# Feature Engineering - Encoding
# ==========================================

import pandas as pd

# Binary Encoding
binary_mappings = {
    'Gender': {'Male': 1, 'Female': 0},
    'Married': {'Yes': 1, 'No': 0},
    'Education': {'Graduate': 1, 'Not Graduate': 0},
    'Self_Employed': {'Yes': 1, 'No': 0},
    'Loan_Status': {'Y': 1, 'N': 0}
}

for column, mapping in binary_mappings.items():
    df[column] = df[column].map(mapping)

# Ordinal Encoding
df['Dependents'] = (
    df['Dependents']
    .replace({'0': 0, '1': 1, '2': 2, '3+': 3})
    .astype(int)
)

# One-Hot Encoding
df = pd.get_dummies(
    df,
    columns=['Property_Area'],
    drop_first=True,
    dtype=int
)

# Verify
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   614 non-null    int64
 1   Married                  614 non-null    int64
 2   Dependents               614 non-null    int64
 3   Education                614 non-null    int64
 4   Self_Employed            614 non-null    int64
 5   ApplicantIncome          614 non-null    int64
 6   CoapplicantIncome        614 non-null    float64
 7   LoanAmount               614 non-null    float64
 8   Loan_Amount_Term         614 non-null    float64
 9   Credit_History           614 non-null    float64
 10  Loan_Status              614 non-null    int64
 11  Property_Area_Semiurban  614 non-null    int64
 12  Property_Area_Urban      614 non-null    int64
dtypes: float64(4), int64(9)
memory usage: 62.5 KB

C:\Users\dell\AppData\Local\Temp\ipykernel_924\2886027260.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace({'0': 0, '1': 1, '2': 2, '3+': 3})

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,128.0,360.0,1.0,1,0,1
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,0,1

In [30]:
df.to_csv("C:/Users/dell/Desktop/Loan_Default_Risk_Prediction/data/processed/loan_feature_engineered.csv", index=False)

In [32]:
df2 = pd.read_csv(
"C:/Users/dell/Desktop/Loan_Default_Risk_Prediction/data/processed/loan_feature_engineered.csv"
)

df2.head()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Property_Area_Semiurban,Property_Area_Urban
0,1,0,0,1,0,5849,0.0,128.0,360.0,1.0,1,0,1
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0,0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1,0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1,0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1,0,1